add reboot check; spelling

diff --git a/files/usr/lib/nagios/plugins/check_mootombo_apt b/files/usr/lib/nagios/plugins/check_mootombo_apt
--- a/files/usr/lib/nagios/plugins/check_mootombo_apt
+++ b/files/usr/lib/nagios/plugins/check_mootombo_apt
@@ -34,35 +34,41 @@ STATUS_OK=0
 STATUS_WARNING=1
 STATUS_CRITICAL=2
 STATUS_UNKNOWN=3
+
 #
 # Query pending updates.
 updates=$(/usr/lib/update-notifier/apt-check 2>&1)
 if [ $? -ne 0 ]; then
-    echo "Querying pending updates failed."
+    echo "*** Querying pending updates failed ***"
     exit $STATUS_UNKNOWN
 fi
 #
 # Check for the case where there are no updates.
 if [ "$updates" = "0;0" ]; then
-    echo "All packages are up-to-date."
+    # Check for the case if the system need to reboot, after updates have all done
+    if [ -f /var/run/reboot-required ]; then
+        echo "*** System restart required ***"
+        exit $STATUS_WARNING
+    fi
+    echo "All packages are up-to-date!"
     exit $STATUS_OK
 fi;
 #
 # Check for pending security updates.
 pending=$(echo "$updates" | cut -d ";" -f 2)
 if [ "$pending" != "0" ]; then
-    echo "$pending security update(s) pending."
+    echo "*** $pending security update(s) pending ***"
     exit $STATUS_CRITICAL
 fi
 #
 # Check for pending non-security updates.
 pending=$(echo "$updates" | cut -d ";" -f 1)
 if [ "$pending" != "0" ]; then
-    echo "$pending non-security update(s) pending."
+    echo "*** $pending non-security update(s) pending ***"
     exit $STATUS_WARNING
 fi
 #
 # If we've gotten here, we did something wrong since our "0;0" check should have
 # matched at the very least.
-echo "Script failed, manual intervention required."
+echo "*** Script failed, manual intervention required ***"
 exit $STATUS_UNKNOWN
